name: Q
favicon: null
layout_spectrum: 0.953787287697196
typography_spectrum: 0.8605211235117167
title: Q
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6e6f71'
    - '#15b5bc'
    - '#000000'
    - '#00ffff'
    - '#0000ff'
  brandStrength: 0.4273485110606998
  lightness: 0.13451786898076534
  saturation: 0.264816636685282
  rhythmicContrast: 0.6746136648580432
purpose: []
